from __future__ import annotations

from typing import Any


BLUEPRINT: list[dict[str, Any]] = [
    {
        'id': 'main_menu',
        'title': 'Главное меню',
        'locale_key': 'MAIN_MENU_TITLE',
        'bot_callback': 'back_to_menu',
        'web_path': '/',
        'hint': 'Стартовый экран бота и личного кабинета, откуда открываются все остальные разделы.',
        'keywords': ('главное меню', 'старт', 'начало', 'домой', 'main menu'),
        'children': [
            {
                'id': 'subscription',
                'title': 'Мои подписки',
                'locale_key': 'MY_SUBSCRIPTIONS_BUTTON',
                'bot_callback': 'menu_subscription',
                'web_path': '/subscription',
                'hint': 'Текущие подписки: срок действия, трафик, устройства, продление и настройки.',
                'keywords': ('подписка', 'мои подписки', 'тариф', 'срок', 'истекает', 'subscription'),
                'children': [
                    {
                        'id': 'subscription_buy',
                        'title': 'Купить подписку',
                        'locale_key': 'MENU_BUY_SUBSCRIPTION',
                        'bot_callback': 'menu_buy',
                        'web_path': '/subscription',
                        'hint': 'Оформление новой подписки: выбор тарифа, периода, стран и количества устройств.',
                        'keywords': ('купить', 'оформить', 'покупка', 'приобрести', 'buy'),
                    },
                    {
                        'id': 'subscription_detail',
                        'title': '[Выберите подписку]',
                        'bot_callback': None,
                        'web_path': '/subscription',
                        'hint': 'Выбор конкретной активной или истекшей подписки из списка для управления.',
                        'keywords': ('выбрать подписку', 'моя подписка', 'управление подпиской'),
                        'children': [
                            {
                                'id': 'subscription_connect',
                                'title': '🔗 Ссылка подключения',
                                'bot_callback': 'subscription_connect',
                                'web_path': '/subscription',
                                'hint': 'Получение индивидуальной ссылки подписки и инструкции по настройке.',
                                'keywords': ('подключиться', 'ссылка подписки', 'конфиг', 'настроить vpn', 'connect'),
                                'children': [
                                    {
                                        'id': 'device_guide_ios',
                                        'title': '📱 iOS (iPhone, iPad)',
                                        'bot_callback': 'device_guide_ios',
                                        'web_path': '/subscription',
                                        'hint': 'Инструкция и приложения для подключения на iOS (Happ, Shadowrocket, Streisand, V2Ray).',
                                        'keywords': ('ios', 'iphone', 'айфон', 'ipad', 'айпад', 'apple'),
                                    },
                                    {
                                        'id': 'device_guide_android',
                                        'title': '🤖 Android',
                                        'bot_callback': 'device_guide_android',
                                        'web_path': '/subscription',
                                        'hint': 'Инструкция и приложения для подключения на Android (Happ, v2rayNG, Nekobox).',
                                        'keywords': ('android', 'андроид', 'v2rayng', 'nekobox', 'samsung', 'xiaomi'),
                                    },
                                    {
                                        'id': 'device_guide_windows',
                                        'title': '💻 Windows',
                                        'bot_callback': 'device_guide_windows',
                                        'web_path': '/subscription',
                                        'hint': 'Инструкция и приложения для подключения на ПК / Windows (Happ, v2rayN, Nekoray, Outline).',
                                        'keywords': ('windows', 'виндовс', 'пк', 'компьютер', 'v2rayn', 'nekoray'),
                                    },
                                    {
                                        'id': 'device_guide_macos',
                                        'title': '🍏 macOS',
                                        'bot_callback': 'device_guide_macos',
                                        'web_path': '/subscription',
                                        'hint': 'Инструкция и приложения для подключения на Mac / macOS (Happ, V2Box, FoXray, Shadowrocket).',
                                        'keywords': ('mac', 'macos', 'макробук', 'макбук', 'v2box', 'foxray'),
                                    },
                                    {
                                        'id': 'device_guide_linux',
                                        'title': '🐧 Linux',
                                        'bot_callback': 'device_guide_linux',
                                        'web_path': '/subscription',
                                        'hint': 'Инструкция и приложения для подключения на Linux (Nekoray, Sing-box).',
                                        'keywords': ('linux', 'линукс', 'ubuntu', 'debian'),
                                    },
                                    {
                                        'id': 'open_subscription_link',
                                        'title': '📋 Показать ссылку подписки',
                                        'bot_callback': 'open_subscription_link',
                                        'web_path': '/subscription',
                                        'hint': 'Прямое отображение скопированной ссылки подписки для вставки вручную.',
                                        'keywords': ('показать ссылку', 'скопировать ссылку', 'ссылка подписки', 'raw link'),
                                    },
                                ],
                            },
                            {
                                'id': 'subscription_extend',
                                'title': '⏰ Продлить подписку',
                                'locale_key': 'MENU_EXTEND_SUBSCRIPTION',
                                'bot_callback': 'subscription_extend',
                                'web_path': '/subscription',
                                'hint': 'Продление выбранной подписки на любой доступный период.',
                                'keywords': ('продлить', 'продление', 'оплатить ещё', 'extend'),
                            },
                            {
                                'id': 'subscription_devices',
                                'title': '📱 Устройства',
                                'bot_callback': 'subscription_devices',
                                'web_path': '/subscription',
                                'hint': 'Просмотр и изменение количества подключённых устройств.',
                                'keywords': ('устройства', 'девайсы', 'лимит устройств', 'devices'),
                            },
                            {
                                'id': 'subscription_autopay',
                                'title': '⚡ Автоплатеж',
                                'bot_callback': 'subscription_autopay',
                                'web_path': '/subscription',
                                'hint': 'Включение и настройка автоматического продления подписки.',
                                'keywords': ('автоплатеж', 'автопродление', 'автосписание', 'autopay'),
                                'children': [
                                    {
                                        'id': 'subscription_autopay_toggle',
                                        'title': 'Включить / Выключить автоплатеж',
                                        'bot_callback': 'autopay_enable',
                                        'web_path': '/subscription',
                                        'hint': 'Переключение активности автоплатежа (Включить / Выключить).',
                                        'keywords': ('включить', 'выключить', 'включить автоплатеж', 'выключить автоплатеж', 'отключить автоплатеж'),
                                    },
                                    {
                                        'id': 'subscription_autopay_days',
                                        'title': '⚙️ Настроить дни',
                                        'bot_callback': 'autopay_days',
                                        'web_path': '/subscription',
                                        'hint': 'Настройка количества дней до окончания подписки, за которое происходит списание.',
                                        'keywords': ('настроить дни', 'за сколько дней', 'дни списания', 'списание за дн'),
                                    },
                                    {
                                        'id': 'subscription_autopay_period',
                                        'title': '📅 Период продления',
                                        'bot_callback': 'autopay_period',
                                        'web_path': '/subscription',
                                        'hint': 'Выбор периода продления подписки при автоматическом списании.',
                                        'keywords': ('период продления', 'период автоплатежа', 'на какой срок продлевать'),
                                    },
                                    {
                                        'id': 'subscription_autopay_sbp',
                                        'title': '⚡ Автопродление через СБП',
                                        'bot_callback': 'sbp_recurring_menu',
                                        'web_path': '/subscription',
                                        'hint': 'Настройка и подключение автопродления подписки через СБП (Систему Быстрых Платежей).',
                                        'keywords': ('автопродление через сбп', 'автопродление сбп', 'автоплатеж сбп', 'сбп автосписание', 'сбп'),
                                    },
                                ],
                            },
                            {
                                'id': 'subscription_traffic',
                                'title': '📊 Трафик',
                                'bot_callback': 'subscription_traffic',
                                'web_path': '/subscription',
                                'hint': 'Раздел работы с трафиком: докупка, сброс или переключение лимита.',
                                'keywords': ('трафик', 'докупить трафик', 'сбросить трафик', 'переключить трафик', 'гб', 'лимит'),
                                'children': [
                                    {
                                        'id': 'subscription_buy_traffic',
                                        'title': '📈 Докупить трафик',
                                        'bot_callback': 'buy_traffic',
                                        'web_path': '/subscription',
                                        'hint': 'Покупка дополнительного пакета трафика к активной подписке.',
                                        'keywords': ('трафик', 'докупить', 'гб', 'закончился трафик', 'traffic'),
                                    },
                                    {
                                        'id': 'subscription_reset_traffic',
                                        'title': '🔄 Сбросить трафик',
                                        'bot_callback': 'subscription_reset_traffic',
                                        'web_path': '/subscription',
                                        'hint': 'Обнуление счётчика израсходованного трафика.',
                                        'keywords': ('сбросить трафик', 'обнулить', 'reset traffic'),
                                    },
                                    {
                                        'id': 'subscription_switch_traffic',
                                        'title': '🔄 Переключить трафик',
                                        'bot_callback': 'subscription_switch_traffic',
                                        'web_path': '/subscription',
                                        'hint': 'Смена тарифного пакета трафика.',
                                        'keywords': ('переключить трафик', 'пакет трафика', 'switch traffic'),
                                    },
                                ],
                            },
                            {
                                'id': 'subscription_revoke',
                                'title': '🔄 Перевыпустить подписку',
                                'locale_key': 'SUBSCRIPTION_REVOKE_BTN',
                                'bot_callback': 'subscription_revoke',
                                'web_path': '/subscription',
                                'hint': 'Перевыпуск ключа / ссылки подключения подписки.',
                                'keywords': ('перевыпустить', 'обновить ключ', 'сбросить ссылку', 'revoke'),
                            },
                            {
                                'id': 'subscription_upgrade',
                                'title': '🔄 Сменить тариф',
                                'locale_key': 'CHANGE_TARIFF_BUTTON',
                                'bot_callback': 'subscription_upgrade',
                                'web_path': '/subscription',
                                'hint': 'Переход на более высокий тариф с пересчётом стоимости.',
                                'keywords': ('улучшить', 'апгрейд', 'сменить тариф', 'upgrade'),
                            },
                        ],
                    },
                    {
                        'id': 'subscription_settings',
                        'title': 'Настройки подписки',
                        'locale_key': 'SUBSCRIPTION_SETTINGS_BUTTON',
                        'bot_callback': 'subscription_settings',
                        'web_path': '/subscription',
                        'hint': 'Раздел с управлением странами и устройствами.',
                        'keywords': ('настройки подписки', 'параметры', 'settings'),
                        'children': [
                            {
                                'id': 'subscription_add_countries',
                                'title': 'Добавить страны',
                                'locale_key': 'ADD_COUNTRIES_BUTTON',
                                'bot_callback': 'subscription_add_countries',
                                'web_path': '/subscription',
                                'hint': 'Подключение дополнительных стран и серверов к подписке.',
                                'keywords': ('страны', 'сервер', 'локации', 'countries'),
                            },
                            {
                                'id': 'subscription_change_devices',
                                'title': 'Изменить устройства',
                                'locale_key': 'CHANGE_DEVICES_BUTTON',
                                'bot_callback': 'subscription_change_devices',
                                'web_path': '/subscription',
                                'hint': 'Изменение лимита одновременных устройств в подписке.',
                                'keywords': ('устройства', 'лимит устройств', 'devices'),
                            },
                            {
                                'id': 'subscription_manage_devices',
                                'title': 'Управление устройствами',
                                'locale_key': 'MANAGE_DEVICES_BUTTON',
                                'bot_callback': 'subscription_manage_devices',
                                'web_path': '/subscription',
                                'hint': 'Просмотр и сброс подключённых устройств.',
                                'keywords': ('сбросить устройство', 'отключить устройство', 'manage devices'),
                            },
                        ],
                    },
                ],
            },
            {
                'id': 'balance',
                'title': 'Баланс',
                'locale_key': 'MENU_BALANCE',
                'bot_callback': 'menu_balance',
                'web_path': '/balance',
                'hint': 'Внутренний баланс аккаунта: пополнение, история операций и сохранённые карты.',
                'keywords': ('баланс', 'деньги', 'счет', 'кошелек', 'balance'),
                'children': [
                    {
                        'id': 'balance_topup',
                        'title': 'Пополнить баланс',
                        'locale_key': 'BALANCE_TOP_UP',
                        'bot_callback': 'balance_topup',
                        'web_path': '/balance/top-up',
                        'hint': 'Выбор способа оплаты и пополнение внутреннего баланса.',
                        'keywords': ('пополнить', 'оплата', 'платеж', 'внести деньги', 'top up'),
                    },
                    {
                        'id': 'balance_history',
                        'title': 'История операций',
                        'locale_key': 'BALANCE_HISTORY',
                        'bot_callback': 'balance_history',
                        'web_path': '/balance',
                        'hint': 'Список всех списаний и пополнений по балансу.',
                        'keywords': ('история', 'транзакции', 'операции', 'чек', 'history'),
                    },
                    {
                        'id': 'saved_cards',
                        'title': 'Привязанные карты',
                        'locale_key': 'SAVED_CARDS_BUTTON',
                        'bot_callback': 'saved_cards_list',
                        'web_path': '/balance',
                        'hint': 'Управление сохранёнными банковскими картами для автоплатежа.',
                        'keywords': ('карта', 'карты', 'отвязать карту', 'saved cards'),
                    },
                ],
            },
            {
                'id': 'promocode',
                'title': 'Промокод',
                'locale_key': 'MENU_PROMOCODE',
                'bot_callback': 'menu_promocode',
                'web_path': '/promocode',
                'hint': 'Ввод и активация промокода на бонус к балансу или дни подписки.',
                'keywords': ('промокод', 'код', 'купон', 'активировать промокод', 'promocode'),
            },
            {
                'id': 'referral',
                'title': 'Партнёрская программа',
                'locale_key': 'MENU_REFERRALS',
                'bot_callback': 'menu_referrals',
                'web_path': '/referral',
                'hint': 'Реферальная программа: приглашения, статистика, начисления и вывод партнёрских средств.',
                'keywords': ('партнерка', 'реферал', 'рефералы', 'приглашение', 'referral'),
                'children': [
                    {
                        'id': 'referral_create_invite',
                        'title': 'Создать приглашение',
                        'locale_key': 'CREATE_INVITE_BUTTON',
                        'bot_callback': 'referral_create_invite',
                        'web_path': '/referral',
                        'hint': 'Получение персональной реферальной ссылки для приглашения друзей.',
                        'keywords': ('пригласить', 'ссылка', 'инвайт', 'invite'),
                    },
                    {
                        'id': 'referral_show_qr',
                        'title': 'QR-код приглашения',
                        'locale_key': 'SHOW_QR_BUTTON',
                        'bot_callback': 'referral_show_qr',
                        'web_path': '/referral',
                        'hint': 'QR-код с реферальной ссылкой.',
                        'keywords': ('qr', 'куар', 'код приглашения'),
                    },
                    {
                        'id': 'referral_list',
                        'title': 'Список рефералов',
                        'locale_key': 'REFERRAL_LIST_BUTTON',
                        'bot_callback': 'referral_list',
                        'web_path': '/referral',
                        'hint': 'Список приглашённых пользователей и их статус.',
                        'keywords': ('мои рефералы', 'кого пригласил', 'referrals list'),
                    },
                    {
                        'id': 'referral_analytics',
                        'title': 'Аналитика партнёрки',
                        'locale_key': 'REFERRAL_ANALYTICS_BUTTON',
                        'bot_callback': 'referral_analytics',
                        'web_path': '/referral',
                        'hint': 'Статистика заработка по партнёрской программе.',
                        'keywords': ('аналитика', 'статистика', 'заработок', 'analytics'),
                    },
                    {
                        'id': 'referral_withdrawal',
                        'title': 'Вывод партнёрских средств',
                        'locale_key': 'REFERRAL_WITHDRAWAL_BUTTON',
                        'bot_callback': 'referral_withdrawal',
                        'web_path': '/referral/withdrawal',
                        'hint': (
                            'Заявка на вывод реферального бонуса. В боте: Главное меню → раздел партнёрской '
                            'программы → кнопка запроса вывода. В личном кабинете: раздел партнёрской программы '
                            '→ вкладка вывода средств.'
                        ),
                        'keywords': (
                            'вывод',
                            'вывести',
                            'выплата',
                            'снять деньги',
                            'реферальный бонус',
                            'withdrawal',
                            'payout',
                        ),
                    },
                    {
                        'id': 'referral_partner',
                        'title': 'Заявка партнёра',
                        'locale_key': 'PARTNER_APPLICATION_BUTTON',
                        'bot_callback': None,
                        'web_path': '/referral/partner',
                        'hint': 'Подача заявки на расширенные партнёрские условия (только в личном кабинете).',
                        'keywords': ('партнер', 'заявка партнера', 'partner'),
                    },
                ],
            },
            {
                'id': 'trial',
                'title': 'Тестовая подписка',
                'locale_key': 'MENU_TRIAL',
                'bot_callback': 'menu_trial',
                'web_path': '/subscription',
                'hint': 'Активация бесплатного пробного периода.',
                'keywords': ('триал', 'пробный', 'тест', 'бесплатно', 'trial'),
                'children': [
                    {
                        'id': 'trial_activate',
                        'title': 'Активировать триал',
                        'locale_key': 'TRIAL_ACTIVATE_BUTTON',
                        'bot_callback': 'trial_activate',
                        'web_path': '/subscription',
                        'hint': 'Кнопка запуска пробного периода.',
                        'keywords': ('активировать триал', 'включить пробный', 'activate trial'),
                    },
                ],
            },
            {
                'id': 'support',
                'title': 'Поддержка',
                'locale_key': 'MENU_SUPPORT',
                'bot_callback': 'menu_support',
                'web_path': '/support',
                'hint': 'Обращение в поддержку: создание тикета, просмотр своих тикетов, контакт с оператором.',
                'keywords': ('поддержка', 'помощь', 'оператор', 'связаться', 'support'),
                'children': [
                    {
                        'id': 'support_create_ticket',
                        'title': 'Создать тикет',
                        'locale_key': 'CREATE_TICKET_BUTTON',
                        'bot_callback': 'create_ticket',
                        'web_path': '/tickets',
                        'hint': 'Создание нового обращения в поддержку.',
                        'keywords': ('тикет', 'обращение', 'жалоба', 'создать тикет', 'ticket'),
                    },
                    {
                        'id': 'support_my_tickets',
                        'title': 'Мои тикеты',
                        'locale_key': 'MY_TICKETS_BUTTON',
                        'bot_callback': 'my_tickets',
                        'web_path': '/tickets',
                        'hint': 'История обращений и ответы операторов.',
                        'keywords': ('мои тикеты', 'мои обращения', 'my tickets'),
                    },
                    {
                        'id': 'support_contact',
                        'title': 'Связаться с поддержкой',
                        'locale_key': 'CONTACT_SUPPORT_BUTTON',
                        'bot_callback': None,
                        'web_path': '/support',
                        'hint': 'Прямой контакт с оператором поддержки.',
                        'keywords': ('оператор', 'живой человек', 'контакт', 'contact support'),
                    },
                ],
            },
            {
                'id': 'info',
                'title': 'Информация',
                'locale_key': 'MENU_INFO',
                'bot_callback': 'menu_info',
                'web_path': '/info',
                'hint': 'Справочный раздел: FAQ, правила, оферта, политика, статус серверов, язык интерфейса.',
                'keywords': ('инфо', 'информация', 'справка', 'info'),
                'children': [
                    {
                        'id': 'info_guides',
                        'title': '📚 Инструкции по настройке',
                        'bot_callback': 'info_guides',
                        'web_path': '/info',
                        'hint': 'Пошаговые инструкции и руководства по настройке приложений (Happ, Shadowrocket, Outline, V2Ray, Amnezia).',
                        'keywords': ('инструкция', 'как настроить', 'гайд', 'клиент', 'happ', 'shadowrocket', 'outline', 'v2ray', 'guides'),
                    },
                    {
                        'id': 'info_faq',
                        'title': 'FAQ',
                        'locale_key': 'MENU_FAQ',
                        'bot_callback': 'menu_faq',
                        'web_path': '/info',
                        'hint': 'Ответы на частые вопросы.',
                        'keywords': ('faq', 'частые вопросы', 'вопрос ответ'),
                    },
                    {
                        'id': 'info_promo_groups',
                        'title': 'Скидки за траты',
                        'locale_key': 'MENU_PROMO_GROUPS_INFO',
                        'bot_callback': 'menu_info_promo_groups',
                        'web_path': '/info',
                        'hint': 'Промогруппы и накопительные скидки за сумму покупок.',
                        'keywords': ('скидки', 'промогруппа', 'уровни', 'discounts'),
                    },
                    {
                        'id': 'info_rules',
                        'title': 'Правила сервиса',
                        'locale_key': 'MENU_RULES',
                        'bot_callback': 'menu_rules',
                        'web_path': '/info',
                        'hint': 'Правила использования сервиса.',
                        'keywords': ('правила', 'условия', 'rules'),
                    },
                    {
                        'id': 'info_public_offer',
                        'title': 'Публичная оферта',
                        'locale_key': 'MENU_PUBLIC_OFFER',
                        'bot_callback': 'menu_public_offer',
                        'web_path': '/info',
                        'hint': 'Текст публичной оферты.',
                        'keywords': ('оферта', 'договор', 'offer'),
                    },
                    {
                        'id': 'info_privacy_policy',
                        'title': 'Политика конфиденциальности',
                        'locale_key': 'MENU_PRIVACY_POLICY',
                        'bot_callback': 'menu_privacy_policy',
                        'web_path': '/info',
                        'hint': 'Политика обработки персональных данных.',
                        'keywords': ('политика', 'конфиденциальность', 'персональные данные', 'privacy'),
                    },
                    {
                        'id': 'info_server_status',
                        'title': 'Статус серверов',
                        'locale_key': 'MENU_SERVER_STATUS',
                        'bot_callback': 'menu_server_status',
                        'web_path': '/info',
                        'hint': 'Текущая доступность серверов и локаций.',
                        'keywords': ('статус', 'сервера', 'доступность', 'не работает', 'server status'),
                    },
                    {
                        'id': 'info_language',
                        'title': 'Язык интерфейса',
                        'locale_key': 'MENU_LANGUAGE',
                        'bot_callback': 'menu_language',
                        'web_path': '/info',
                        'hint': 'Смена языка бота и личного кабинета.',
                        'keywords': ('язык', 'сменить язык', 'language'),
                    },
                ],
            },
            {
                'id': 'contests',
                'title': 'Конкурсы',
                'locale_key': 'CONTESTS_BUTTON',
                'bot_callback': 'contests_menu',
                'web_path': '/contests',
                'hint': 'Активные конкурсы и розыгрыши.',
                'keywords': ('конкурс', 'розыгрыш', 'приз', 'contest'),
            },
            {
                'id': 'profile',
                'title': 'Личный кабинет',
                'locale_key': 'MENU_PROFILE',
                'bot_callback': 'menu_profile',
                'web_path': '/profile',
                'hint': 'Профиль пользователя в веб-кабинете: данные аккаунта, привязки, уведомления.',
                'keywords': ('профиль', 'кабинет', 'аккаунт', 'profile'),
                'children': [
                    {
                        'id': 'profile_notifications',
                        'title': 'Уведомления',
                        'locale_key': 'NOTIFICATIONS_BUTTON',
                        'bot_callback': None,
                        'web_path': '/notifications',
                        'hint': 'Настройки уведомлений и список полученных сообщений (личный кабинет).',
                        'keywords': ('уведомления', 'оповещения', 'notifications'),
                    },
                    {
                        'id': 'profile_news',
                        'title': 'Новости',
                        'locale_key': 'NEWS_BUTTON',
                        'bot_callback': None,
                        'web_path': '/news',
                        'hint': 'Лента новостей сервиса (личный кабинет).',
                        'keywords': ('новости', 'анонсы', 'news'),
                    },
                    {
                        'id': 'profile_gift',
                        'title': 'Подарочные подписки',
                        'locale_key': 'GIFT_BUTTON',
                        'bot_callback': None,
                        'web_path': '/gift',
                        'hint': 'Покупка и активация подарочной подписки (личный кабинет).',
                        'keywords': ('подарок', 'подарить', 'gift'),
                    },
                    {
                        'id': 'profile_wheel',
                        'title': 'Колесо фортуны',
                        'locale_key': 'WHEEL_BUTTON',
                        'bot_callback': None,
                        'web_path': '/wheel',
                        'hint': 'Розыгрыш бонусов колесом фортуны (личный кабинет).',
                        'keywords': ('колесо', 'фортуна', 'крутить', 'wheel'),
                    },
                    {
                        'id': 'profile_coupon',
                        'title': 'Купоны',
                        'locale_key': 'COUPON_BUTTON',
                        'bot_callback': None,
                        'web_path': '/coupon',
                        'hint': 'Активация купонов (личный кабинет).',
                        'keywords': ('купон', 'coupon'),
                    },
                    {
                        'id': 'profile_polls',
                        'title': 'Опросы',
                        'locale_key': 'POLLS_BUTTON',
                        'bot_callback': None,
                        'web_path': '/polls',
                        'hint': 'Участие в опросах сервиса (личный кабинет).',
                        'keywords': ('опрос', 'голосование', 'poll'),
                    },
                ],
            },
        ],
    },
]


CALLBACK_HINTS: dict[str, str] = {
    'menu_balance': 'balance',
    'balance_topup': 'balance_topup',
    'balance_history': 'balance_history',
    'saved_cards_list': 'saved_cards',
    'menu_subscription': 'subscription',
    'subscription': 'subscription',
    'subscription_connect': 'subscription_connect',
    'device_guide_ios': 'device_guide_ios',
    'device_guide_android': 'device_guide_android',
    'device_guide_windows': 'device_guide_windows',
    'device_guide_macos': 'device_guide_macos',
    'device_guide_linux': 'device_guide_linux',
    'open_subscription_link': 'open_subscription_link',
    'menu_buy': 'subscription_buy',
    'subscription_extend': 'subscription_extend',
    'subscription_upgrade': 'subscription_upgrade',
    'buy_traffic': 'subscription_buy_traffic',
    'subscription_traffic': 'subscription_traffic',
    'subscription_autopay': 'subscription_autopay',
    'autopay_enable': 'subscription_autopay_toggle',
    'autopay_disable': 'subscription_autopay_toggle',
    'autopay_days': 'subscription_autopay_days',
    'autopay_period': 'subscription_autopay_period',
    'sbp_recurring_menu': 'subscription_autopay_sbp',
    'subscription_settings': 'subscription_settings',
    'subscription_add_countries': 'subscription_add_countries',
    'subscription_change_devices': 'subscription_change_devices',
    'subscription_manage_devices': 'subscription_manage_devices',
    'subscription_reset_traffic': 'subscription_reset_traffic',
    'subscription_switch_traffic': 'subscription_switch_traffic',
    'subscription_revoke': 'subscription_revoke',
    'menu_promocode': 'promocode',
    'menu_referrals': 'referral',
    'menu_referral': 'referral',
    'referral_create_invite': 'referral_create_invite',
    'referral_show_qr': 'referral_show_qr',
    'referral_list': 'referral_list',
    'referral_analytics': 'referral_analytics',
    'referral_withdrawal': 'referral_withdrawal',
    'menu_trial': 'trial',
    'trial_activate': 'trial_activate',
    'menu_support': 'support',
    'create_ticket': 'support_create_ticket',
    'my_tickets': 'support_my_tickets',
    'menu_info': 'info',
    'info_guides': 'info_guides',
    'menu_faq': 'info_faq',
    'menu_info_promo_groups': 'info_promo_groups',
    'menu_rules': 'info_rules',
    'menu_public_offer': 'info_public_offer',
    'menu_privacy_policy': 'info_privacy_policy',
    'menu_server_status': 'info_server_status',
    'menu_language': 'info_language',
    'contests_menu': 'contests',
    'menu_profile': 'profile',
    'back_to_menu': 'main_menu',
}
