from __future__ import annotations

from typing import Any


BLUEPRINT: list[dict[str, Any]] = [{'id': 'main_menu',
  'title': 'ГЛАВНОЕ МЕНЮ (Стартовый экран)',
  'bot_callback': 'main_menu',
  'web_path': '/',
  'hint': 'Главный экран бота или веб-кабинета.',
  'keywords': ('главное меню', 'меню', 'начало', 'старт', 'main menu'),
  'children': [{'id': 'menu_connect',
                'title': 'Подключиться',
                'bot_callback': None,
                'bot_label': 'Подключиться',
                'web_path': '/subscription',
                'hint': 'Прямая ссылка для перехода к настройке подключения (выдаёт реквизиты).',
                'keywords': ('подключиться', 'подключить', 'connect')},
               {'id': 'subscription',
                'title': 'Мои подписки',
                'bot_callback': 'menu_subscription',
                'web_path': '/subscription',
                'hint': 'Список всех подписок пользователя.',
                'keywords': ('мои подписки', 'подписки', 'список подписок', 'subscriptions'),
                'children': [{'id': 'subs_buy_subscription',
                              'title': 'Купить подписку',
                              'bot_callback': 'menu_buy',
                              'web_path': '/subscription',
                              'hint': 'Переход к выбору тарифа и покупке новой подписки.',
                              'keywords': ('купить подписку', 'оформить подписку', 'buy')},
                             {'id': 'subscription_detail',
                              'title': '[Выберите подписку]',
                              'bot_label': '[Выберите подписку]',
                              'bot_callback': None,
                              'web_path': '/subscription',
                              'hint': 'Выбор конкретной подписки (например, "Семейный") для управления.',
                              'keywords': ('выбрать подписку', 'моя подписка', 'управление подпиской'),
                              'children': [{'id': 'subscription_connect',
                                            'title': 'Ссылка подключения',
                                            'bot_callback': 'subscription_connect',
                                            'web_path': '/subscription',
                                            'hint': 'Отображение индивидуальной ссылки подписки для подключения.',
                                            'keywords': ('ссылка подключения', 'ссылка подписки', 'настроить vpn')},
                                           {'id': 'subscription_extend',
                                            'title': 'Продлить',
                                            'bot_callback': 'subscription_extend',
                                            'web_path': '/subscription',
                                            'hint': 'Продление выбранной подписки на новый период.',
                                            'keywords': ('продлить', 'продление', 'оплатить ещё', 'extend')},
                                           {'id': 'subscription_devices',
                                            'title': 'Устройства',
                                            'bot_callback': 'subscription_devices',
                                            'web_path': '/subscription',
                                            'hint': 'Текущий лимит устройств, управление и добавление.',
                                            'keywords': ('устройства', 'девайсы', 'лимит устройств', 'devices'),
                                            'children': [{'id': 'subscription_add_devices',
                                                          'title': 'Докупить устройства',
                                                          'bot_callback': 'subscription_add_devices',
                                                          'web_path': '/subscription',
                                                          'hint': 'Обновление лимита устройств к текущей подписке.',
                                                          'keywords': ('докупить устройства', 'добавить устройство')},
                                                         {'id': 'subscription_manage_devices',
                                                          'title': 'Управление устройствами',
                                                          'bot_callback': 'subscription_manage_devices',
                                                          'web_path': '/subscription',
                                                          'hint': 'Просмотр списка устройств и сброс.',
                                                          'keywords': ('управление устройствами',
                                                                       'список устройств',
                                                                       'сбросить устройство'),
                                                          'children': [{'id': 'subscription_reset_device',
                                                                        'title': '[Выберите устройство для сброса]',
                                                                        'bot_label': '[Выберите устройство для сброса]',
                                                                        'bot_callback': None,
                                                                        'web_path': '/subscription',
                                                                        'hint': 'Отключение συγκεκριтного устройства.',
                                                                        'keywords': ('выберите устройство для сброса',
                                                                                     'отключить устройство')},
                                                                       {'id': 'reset_all_devices',
                                                                        'title': 'Сбросить все устройства',
                                                                        'bot_callback': 'reset_all_devices',
                                                                        'web_path': '/subscription',
                                                                        'hint': 'Сброс всех активных подключений '
                                                                                'устройств к подписке.',
                                                                        'keywords': ('сбросить все устройства',
                                                                                     'сброс сессий',
                                                                                     'reset all devices')}]}]},
                                           {'id': 'subscription_autopay',
                                            'title': 'Автоплатеж',
                                            'bot_callback': 'subscription_autopay',
                                            'web_path': '/subscription',
                                            'hint': 'Настройка автоматического продления подписки.',
                                            'keywords': ('автоплатеж', 'автопродление', 'автосписание', 'autopay'),
                                            'children': [{'id': 'subscription_autopay_toggle',
                                                          'title': 'Включить / Выключить',
                                                          'bot_callback': 'autopay_enable',
                                                          'web_path': '/subscription',
                                                          'hint': 'Переключение активности автоплатежа.',
                                                          'keywords': ('включить',
                                                                       'выключить',
                                                                       'включить автоплатеж',
                                                                       'выключить автоплатеж')},
                                                         {'id': 'subscription_autopay_days',
                                                          'title': 'Настроить дни',
                                                          'bot_callback': 'autopay_days',
                                                          'web_path': '/subscription',
                                                          'hint': 'Настройка количества дней до окончания подписки для '
                                                                  'списания.',
                                                          'keywords': ('настроить дни',
                                                                       'за сколько дней',
                                                                       'дни списания')},
                                                         {'id': 'subscription_autopay_sbp',
                                                          'title': 'Автопродление через СБП',
                                                          'bot_callback': 'sbp_recurring_menu',
                                                          'web_path': '/subscription',
                                                          'hint': 'Настройка автопродления через СБП.',
                                                          'keywords': ('автопродление через сбп',
                                                                       'сбп автосписание',
                                                                       'сбп')}]},
                                           {'id': 'subscription_traffic',
                                            'title': 'Трафик',
                                            'bot_callback': 'subscription_traffic',
                                            'web_path': '/subscription',
                                            'hint': 'Просмотр и докупка трафика.',
                                            'keywords': ('трафик', 'гб', 'лимит', 'traffic')},
                                           {'id': 'subscription_revoke',
                                            'title': 'Перевыпустить',
                                            'bot_callback': 'subscription_revoke',
                                            'web_path': '/subscription',
                                            'hint': 'Перевыпуск ключа / ссылки подключения подписки сбросом устройств.',
                                            'keywords': ('перевыпустить',
                                                         'обновить ключ',
                                                         'сбросить ссылку',
                                                         'revoke')}]}]},
               {'id': 'balance',
                'title': 'Баланс',
                'bot_callback': 'menu_balance',
                'web_path': '/balance',
                'hint': 'Отображает текущий баланс аккаунта.',
                'keywords': ('баланс', 'деньги', 'счет', 'кошелек', 'balance'),
                'children': [{'id': 'balance_history',
                              'title': 'История',
                              'bot_callback': 'balance_history',
                              'web_path': '/balance',
                              'hint': 'Список транзакций, списаний и пополнений.',
                              'keywords': ('история', 'транзакции', 'операции', 'чек', 'history')},
                             {'id': 'balance_topup',
                              'title': 'Пополнить',
                              'bot_callback': 'balance_topup',
                              'web_path': '/balance/top-up',
                              'hint': 'Выбор способа оплаты для пополнения баланса.',
                              'keywords': ('пополнить', 'оплата', 'платеж', 'внести деньги', 'top up'),
                              'children': [{'id': 'topup_sbp',
                                            'title': 'СБП',
                                            'bot_callback': 'topup_sbp',
                                            'web_path': '/balance',
                                            'hint': 'Пополнение баланса через СБП.',
                                            'keywords': ('сбп', 'qr', 'система быстрых платежей')},
                                           {'id': 'topup_card',
                                            'title': 'Банковская карта',
                                            'bot_callback': 'topup_card',
                                            'web_path': '/balance',
                                            'hint': 'Пополнение баланса банковскими картами.',
                                            'keywords': ('карта', 'банковская карта')},
                                           {'id': 'topup_sbp_alt',
                                            'title': 'СБП #2',
                                            'bot_callback': 'topup_sbp_alt',
                                            'web_path': '/balance',
                                            'hint': 'Альтернативный шлюз пополнения через СБП.',
                                            'keywords': ('сбп 2', 'сбп альтернативный')},
                                           {'id': 'topup_stars',
                                            'title': 'Telegram Stars',
                                            'bot_callback': 'topup_stars',
                                            'web_path': '/balance',
                                            'hint': 'Оплата внутренними звёздами Telegram Stars.',
                                            'keywords': ('stars', 'звезды', 'телеграм звезды', 'telegram stars')},
                                           {'id': 'topup_crypto',
                                            'title': 'Криптовалюта',
                                            'bot_callback': 'topup_crypto',
                                            'web_path': '/balance',
                                            'hint': 'Пополнение криптовалютой.',
                                            'keywords': ('крипта', 'криптовалюта')},
                                           {'id': 'topup_foreign_card',
                                            'title': 'Иностранная карта',
                                            'bot_callback': 'topup_foreign_card',
                                            'web_path': '/balance',
                                            'hint': 'Оплата банковскими картами зарубежных банков.',
                                            'keywords': ('иностранная карта', 'зарубежная карта')},
                                           {'id': 'topup_support',
                                            'title': 'Через поддержку',
                                            'bot_callback': 'topup_support',
                                            'web_path': '/support',
                                            'hint': 'Ручное пополнение баланса через обращение в техподдержку.',
                                            'keywords': ('через поддержку', 'ручное пополнение')}]},
                             {'id': 'saved_cards',
                              'title': 'Привязанные карты',
                              'bot_callback': 'saved_cards_list',
                              'web_path': '/balance',
                              'hint': 'Управление привязанными банковскими картами.',
                              'keywords': ('привязанные карты', 'отвязать карту', 'saved cards')}]},
               {'id': 'promocode',
                'title': 'Промокод',
                'bot_callback': 'menu_promocode',
                'web_path': '/promocode',
                'hint': 'Поле ввода промокода.',
                'keywords': ('промокод', 'код', 'купон', 'активировать промокод', 'promocode')},
               {'id': 'referral',
                'title': 'Партнерка',
                'bot_callback': 'menu_referrals',
                'web_path': '/referral',
                'hint': 'Реферальная программа: доходы, рефералы и ссылки.',
                'keywords': ('партнерка', 'реферал', 'рефералы', 'приглашение', 'referral'),
                'children': [{'id': 'referral_create_invite',
                              'title': 'Создать приглашение',
                              'bot_callback': 'referral_create_invite',
                              'web_path': '/referral',
                              'hint': 'Отображает вашу реферальную ссылку (бот и веб).',
                              'keywords': ('создать приглашение', 'пригласить', 'ссылка', 'инвайт')},
                             {'id': 'referral_show_qr',
                              'title': 'Показать QR код',
                              'bot_callback': 'referral_show_qr',
                              'web_path': '/referral',
                              'hint': 'Показ QR-кода с реферальной ссылкой.',
                              'keywords': ('показать qr код', 'qr', 'куар', 'код приглашения')},
                             {'id': 'referral_list',
                              'title': 'Список рефералов',
                              'bot_callback': 'referral_list',
                              'web_path': '/referral',
                              'hint': 'Список приглашённых пользователей.',
                              'keywords': ('список рефералов', 'мои рефералы', 'кого пригласил')},
                             {'id': 'referral_analytics',
                              'title': 'Аналитика',
                              'bot_callback': 'referral_analytics',
                              'web_path': '/referral',
                              'hint': 'Статистика заработка по партнерке.',
                              'keywords': ('аналитика', 'статистика партнерки')},
                             {'id': 'referral_withdrawal',
                              'title': 'Запросить вывод',
                              'bot_callback': 'referral_withdrawal',
                              'web_path': '/referral/withdrawal',
                              'hint': 'Заявка на вывод заработанных реферальных бонусов.',
                              'keywords': ('запросить вывод', 'вывод средств', 'выплата')}]},
               {'id': 'info',
                'title': 'Инфо',
                'bot_callback': 'menu_info',
                'web_path': '/info',
                'hint': 'Скидки, политики, оферта и язык.',
                'keywords': ('инфо', 'информация', 'справка', 'info'),
                'children': [{'id': 'info_promo_groups',
                              'title': 'Скидки за траты',
                              'bot_callback': 'menu_info_promo_groups',
                              'web_path': '/info',
                              'hint': 'Информация о накопительных скидках.',
                              'keywords': ('скидки за траты', 'промогруппа', 'скидки')},
                             {'id': 'info_privacy_policy',
                              'title': 'Политика конф.',
                              'bot_callback': 'menu_privacy_policy',
                              'web_path': '/info',
                              'hint': 'Политика обработки конфиденциальных данных.',
                              'keywords': ('политика конф', 'политика', 'конфиденциальность')},
                             {'id': 'info_public_offer',
                              'title': 'Оферта',
                              'bot_callback': 'menu_public_offer',
                              'web_path': '/info',
                              'hint': 'Текст публичной оферты.',
                              'keywords': ('оферта', 'договор')},
                             {'id': 'info_language',
                              'title': 'Язык',
                              'bot_callback': 'menu_language',
                              'web_path': '/info',
                              'hint': 'Смена языка интерфейса.',
                              'keywords': ('язык', 'сменить язык', 'language')}]},
               {'id': 'support',
                'title': 'Поддержка',
                'bot_callback': 'menu_support',
                'web_path': '/support',
                'hint': 'Обращение к оператору поддержки или управление тикетами.',
                'keywords': ('поддержка', 'помощь', 'связаться')},
               {'id': 'admin',
                'title': 'Админ панель',
                'bot_callback': 'admin_menu',
                'web_path': '/admin',
                'hint': 'Управление ботом для администраторов.',
                'keywords': ('админ', 'админ панель', 'управление')}]}]


CALLBACK_HINTS: dict[str, str] = {'menu_balance': 'balance',
 'balance_topup': 'balance_topup',
 'topup_sbp': 'topup_sbp',
 'topup_card': 'topup_card',
 'topup_sbp_alt': 'topup_sbp_alt',
 'topup_stars': 'topup_stars',
 'topup_crypto': 'topup_crypto',
 'topup_foreign_card': 'topup_foreign_card',
 'topup_support': 'topup_support',
 'balance_history': 'balance_history',
 'saved_cards_list': 'saved_cards',
 'menu_subscription': 'subscription',
 'subscription': 'subscription',
 'subscription_connect': 'subscription_connect',
 'open_subscription_link': 'open_subscription_link',
 'menu_buy': 'subscription_buy',
 'subscription_extend': 'subscription_extend',
 'subscription_devices': 'subscription_devices',
 'subscription_add_devices': 'subscription_add_devices',
 'subscription_manage_devices': 'subscription_manage_devices',
 'reset_all_devices': 'reset_all_devices',
 'subscription_upgrade': 'subscription_upgrade',
 'buy_traffic': 'subscription_buy_traffic',
 'subscription_traffic': 'subscription_traffic',
 'subscription_autopay': 'subscription_autopay',
 'autopay_enable': 'subscription_autopay_toggle',
 'autopay_disable': 'subscription_autopay_toggle',
 'autopay_days': 'subscription_autopay_days',
 'autopay_period': 'subscription_autopay_period',
 'sbp_recurring_menu': 'subscription_autopay_sbp',
 'subscription_settings': 'subscription_settings',
 'subscription_add_countries': 'subscription_add_countries',
 'subscription_change_devices': 'subscription_change_devices',
 'subscription_reset_traffic': 'subscription_reset_traffic',
 'subscription_switch_traffic': 'subscription_switch_traffic',
 'subscription_revoke': 'subscription_revoke',
 'menu_promocode': 'promocode',
 'menu_referrals': 'referral',
 'menu_referral': 'referral',
 'referral_create_invite': 'referral_create_invite',
 'referral_show_qr': 'referral_show_qr',
 'referral_list': 'referral_list',
 'referral_analytics': 'referral_analytics',
 'referral_withdrawal': 'referral_withdrawal',
 'menu_support': 'support',
 'menu_info': 'info',
 'menu_info_promo_groups': 'info_promo_groups',
 'menu_public_offer': 'info_public_offer',
 'menu_privacy_policy': 'info_privacy_policy',
 'menu_language': 'info_language',
 'back_to_menu': 'main_menu'}

